# genera el token.
- name: get join command
  shell: kubeadm token create --print-join-command # genera el token.
  register: join_command_raw # lo registra en esta lista.

# De la lista join_command_raw extrae el token y lo guarda'set_fact' (leer doc Ansible)
- name: set join command
  set_fact:
    join_command: "{{ join_command_raw.stdout_lines[0] }}"

# la set_fact es una variable en tiempo de ejecuci칩n del playbook.
# y estar치 disponible su acceso mientras dure la ejecuci칩n del playbook
# pudiendo ser llamado desde otras partes del c칩digo, tal como se ve en
# el role joinning_to_cluster/tasks/joining_nodes.yaml
