- name: Firewalld rules workers
  firewalld:
    permanent: yes
    immediate: yes
    port: "{{item.port}}/{{item.proto}}"
    state: "{{ item.state }}"
  with_items:
    - "{{ worker_firewalld_port_rules }}"
  become: yes

- name: enabling rich rules workers
  firewalld:
    permanent: yes
    immediate: yes
    rich_rule: "{{ item }}"
    state: enabled
  with_items:
    - "{{ worker_firewalld_rich_rules }}"
  become: yes
