---
- name: Adding Users
  user: 
    name: "{{ item.name }}"
    create_home: yes
    comment: "Created with Ansible"
    password: "{{ 'Passw0rd' | password_hash('sha512') }}"
    update_password: on_create
  with_items: "{{ users }}"
  register: user_status

- name: Force change password
  shell: chage -d 0 "{{ item.name }}"
  with_items:
    - "{{ users }}"
  when: user_status.changed 

- name: Add users to sudoers
  copy:
    content: "{{ item.name }} ALL=(ALL:ALL) NOPASSWD:ALL"
    dest: /etc/sudoers.d/{{ item.name }}
    mode: 0440
  with_items: "{{ users }}"
